[package]
name = "scc"
version = "0.1.0"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.11"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
lazy_static = "1.4.0"
